#ifndef T_TFT_IMAGE_H
#define T_TFT_IMAGE_H

enum TftImage {
    IMAGE_THERMOMETER,
    
    IMAGE_THERMOMETER_FULL,
    IMAGE_THERMOMETER_THREE_QUARTER,
    IMAGE_THERMOMETER_HALF,
    IMAGE_THERMOMETER_QUARTER,
    IMAGE_THERMOMETER_EMPTY,
    
    IMAGE_WIFI_OFF,
    IMAGE_SERVER_OFF,
    IMAGE_RECEIVER_OFF,

    IMAGE_ORDER_PROGRAMME,
    IMAGE_ORDER_FORCED,
    IMAGE_ORDER_POWER_OFF
};

#endif