#ifdef ESP8266

#define PIN_TFT_BRIGHTNESS D1
#define PIN_BUTTON_MORE D3
#define PIN_BUTTON_MINUS D6
#define PIN_BUTTON_OK D2

#else

#define SHT_ADDR 0x44
#define PIN_TFT_BRIGHTNESS 16
#define PIN_BUTTON_MORE 25
#define PIN_BUTTON_MINUS 26
#define PIN_BUTTON_OK 27

#endif