#ifndef T_HEATING_TYPE_H
#define T_HEATING_TYPE_H

enum HeatingType {
    HEATING_PROGRAMME,
    HEATING_POWER_OFF,
    HEATING_FORCED_UNTIL,
    HEATING_FORCED_NEXT_ORDER,
    HEATING_FORCED_ALWAYS
};

#endif